services:
  postgres:
    image: postgres:16
    container_name: sentinelai-db
    environment:
      POSTGRES_USER: sentinelai
      POSTGRES_PASSWORD: sentinelai123
      POSTGRES_DB: sentinelai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: sentinelai-api
    environment:
      DATABASE_URL: postgresql://sentinelai:sentinelai123@postgres:5432/sentinelai
      API_KEY: uma-chave-bem-dificil-de-adivinhar-123
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

volumes:
  pgdata:
